In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Complete Machine Learning & Data Science with Python | A-Z

1. *First Contact*
2. *Installations for Python*
3. Evaluation Metrics
4. Supervised Learning
5. Linear Regression Algorithm
6. Bias Variance Tade-Off
7. Logistic Regression Algorithm
8. K-fold Cross-Validation
9. K Nearest Neignbors Algorithm
10. Hyperparameter Optimization
11. Decision Tree Algorithm
12. Random Forest Algorithm
13. Support Vector Machine Algorithm
14. Usupervised Learning
15. K Means Clusterins Algorithm
16. Hierarchical Clustering Algorithm
17. Principal Conponent Analysis (PCA)
18. Recommender System Algorithm
19. Extra

# Evaluation Metrics

In [2]:
!pip install scikit-learn
#from sklearn.family import Model_Object
from sklearn.linear_model import LinearRegression

In [3]:
example_model = LinearRegression()
example_model

new_example_model = LinearRegression(fit_intercept=False, positive=True, copy_X=False)
new_example_model

LinearRegression(copy_X=False, fit_intercept=False, positive=True)

In [4]:
import numpy as np

X = np.arange(30).reshape((10,3))
y = range(10)

X # independent variable

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [5]:
y # dependent variable

range(0, 10)

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4)

In [8]:
X_train

array([[12, 13, 14],
       [24, 25, 26],
       [ 3,  4,  5],
       [27, 28, 29],
       [ 6,  7,  8],
       [18, 19, 20]])

In [9]:
X_test

array([[21, 22, 23],
       [ 0,  1,  2],
       [15, 16, 17],
       [ 9, 10, 11]])

In [10]:
y_train

[4, 8, 1, 9, 2, 6]

In [11]:
y_test

[7, 0, 5, 3]

In [12]:
example_model.fit(X_train, y_train)

LinearRegression()

In [13]:
example_predictions = example_model.predict(X_test)
example_predictions

array([ 7.00000000e+00, -1.44328993e-15,  5.00000000e+00,  3.00000000e+00])